# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Patrick N. McKinney, Cartographer &#38; Developer
description: Patrick N. McKinney is a cartographer and developer interested in telling the stories of communities through maps and technology.
baseurl: "/website-live-test" # the subpath of your site, e.g. /blog
url: "https://pnmcartodesign.com" # the base hostname & protocol for your site
>>>>>>> cb423f7afc94fa8cb1fddc9e42512f8d8b458dab
# Build settings
markdown: kramdown
